### ISSUE TITLE
Bug when accessing boolean field ?

### ISSUE THREAD

**Issue by Choko256** [QuentinJanuel/AccessDB-parser#2]
When trying to access a table with a boolean field, it fails with the following error : 

```
Failed to parse bool field, Column not found in nullTable column: My_Field_Name, column id: 5, nullTable:
```

The null table seems to never being feed correctly, the loop in the `parseRow` function should go from 0 to `nullTableBuffer.length * 8` and not `nullTable.length * 8`.

**Comment by QuentinJanuel** [comment]
Merged
